# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ddf18ec0057cba78016d276cde4a19e117a8281b312767f35fb321777630a9cc92627bf4565fdc5a70dcf3900982762c9dae5c49d5b2125626eaa9118b00209

test:
  secret_key_base: afed772fd17f29d0a076944a39fbaa18ee0585a75f781eff2bd17ded7c66da3a1bcadfea35ee112a88e0f0e75d81a5b0fdcf1df894bea0c1b84a4725dbdca668

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
